[package]
name = "hr-system"
version = "0.1.0"
edition = "2018"

[lib]
name = "hrsystem"
path = "src/lib.rs"

[[bin]]
name = "cli"
path = "src/bin.rs"

[dependencies]
promptly = "0.3"
lazy_static = "1.4"
rusqlite = "0.25"
